package com.xcrm.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrdpic<M extends BasePrdpic<M>> extends Model<M> implements IBean {

	public void setIdprdpic(java.lang.Integer idprdpic) {
		set("idprdpic", idprdpic);
	}

	public java.lang.Integer getIdprdpic() {
		return get("idprdpic");
	}

	public void setFielname(java.lang.String fielname) {
		set("fielname", fielname);
	}

	public java.lang.String getFielname() {
		return get("fielname");
	}

	public void setPrdid(java.lang.Integer prdid) {
		set("prdid", prdid);
	}

	public java.lang.Integer getPrdid() {
		return get("prdid");
	}

}
