package com.xcrm.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayment<M extends BasePayment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCustomerid(java.lang.Integer customerid) {
		set("customerid", customerid);
	}

	public java.lang.Integer getCustomerid() {
		return get("customerid");
	}

	public void setPaymenttype(java.lang.Integer paymenttype) {
		set("paymenttype", paymenttype);
	}

	public java.lang.Integer getPaymenttype() {
		return get("paymenttype");
	}

	public void setPaid(java.math.BigDecimal paid) {
		set("paid", paid);
	}

	public java.math.BigDecimal getPaid() {
		return get("paid");
	}

	public void setComments(java.lang.String comments) {
		set("comments", comments);
	}

	public java.lang.String getComments() {
		return get("comments");
	}

	public void setPaymenttime(java.util.Date paymenttime) {
		set("paymenttime", paymenttime);
	}

	public java.util.Date getPaymenttime() {
		return get("paymenttime");
	}

	public void setOrderno(java.lang.Long orderno) {
		set("orderno", orderno);
	}

	public java.lang.Long getOrderno() {
		return get("orderno");
	}

}
