package com.xcrm.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWorkitemallocation<M extends BaseWorkitemallocation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setWorkitem(java.lang.Integer workitem) {
		set("workitem", workitem);
	}

	public java.lang.Integer getWorkitem() {
		return get("workitem");
	}

	public void setWorker(java.lang.Integer worker) {
		set("worker", worker);
	}

	public java.lang.Integer getWorker() {
		return get("worker");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return get("weight");
	}

	public void setSpendtime(java.lang.Double spendtime) {
		set("spendtime", spendtime);
	}

	public java.lang.Double getSpendtime() {
		return get("spendtime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
