package com.xcrm.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setBarCode(java.lang.String barCode) {
		set("barCode", barCode);
	}

	public java.lang.String getBarCode() {
		return get("barCode");
	}

	public void setCid(java.lang.Integer cid) {
		set("cid", cid);
	}

	public java.lang.Integer getCid() {
		return get("cid");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public void setPeriod(java.lang.String period) {
		set("period", period);
	}

	public java.lang.String getPeriod() {
		return get("period");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}

	public java.lang.String getDepartment() {
		return get("department");
	}

	public void setPoint(java.lang.String point) {
		set("point", point);
	}

	public java.lang.String getPoint() {
		return get("point");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setTtt(java.util.Date ttt) {
		set("ttt", ttt);
	}

	public java.util.Date getTtt() {
		return get("ttt");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public void setEditdate(java.util.Date editdate) {
		set("editdate", editdate);
	}

	public java.util.Date getEditdate() {
		return get("editdate");
	}

	public void setCreateuser(java.lang.Integer createuser) {
		set("createuser", createuser);
	}

	public java.lang.Integer getCreateuser() {
		return get("createuser");
	}

	public void setEdituser(java.lang.Integer edituser) {
		set("edituser", edituser);
	}

	public java.lang.Integer getEdituser() {
		return get("edituser");
	}

	public void setPicture(java.lang.String picture) {
		set("picture", picture);
	}

	public java.lang.String getPicture() {
		return get("picture");
	}

}
