package com.xcrm.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWorkflow<M extends BaseWorkflow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setBookitem(java.lang.Integer bookitem) {
		set("bookitem", bookitem);
	}

	public java.lang.Integer getBookitem() {
		return get("bookitem");
	}

	public void setIndex(java.lang.Integer index) {
		set("index", index);
	}

	public java.lang.Integer getIndex() {
		return get("index");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setProgress(java.lang.Integer progress) {
		set("progress", progress);
	}

	public java.lang.Integer getProgress() {
		return get("progress");
	}

	public void setWorkflowtemplate(java.lang.Integer workflowtemplate) {
		set("workflowtemplate", workflowtemplate);
	}

	public java.lang.Integer getWorkflowtemplate() {
		return get("workflowtemplate");
	}

}
