package com.xcrm.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAttributevalue<M extends BaseAttributevalue<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCategory(java.lang.Integer category) {
		set("category", category);
	}

	public java.lang.Integer getCategory() {
		return get("category");
	}

	public void setAttributeid(java.lang.Integer attributeid) {
		set("attributeid", attributeid);
	}

	public java.lang.Integer getAttributeid() {
		return get("attributeid");
	}

	public void setObjectid(java.lang.Integer objectid) {
		set("objectid", objectid);
	}

	public java.lang.Integer getObjectid() {
		return get("objectid");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}

	public java.lang.String getValue() {
		return get("value");
	}

}
