package com.xcrm.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductpic<M extends BaseProductpic<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setFielname(java.lang.String fielname) {
		set("fielname", fielname);
	}

	public java.lang.String getFielname() {
		return get("fielname");
	}

	public void setProductid(java.lang.Integer productid) {
		set("productid", productid);
	}

	public java.lang.Integer getProductid() {
		return get("productid");
	}

}
