package com.xcrm.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setBarcode(java.lang.String barcode) {
		set("barcode", barcode);
	}

	public java.lang.String getBarcode() {
		return get("barcode");
	}

	public void setLevel1category(java.lang.Integer level1category) {
		set("level1category", level1category);
	}

	public java.lang.Integer getLevel1category() {
		return get("level1category");
	}

	public void setLevel2category(java.lang.Integer level2category) {
		set("level2category", level2category);
	}

	public java.lang.Integer getLevel2category() {
		return get("level2category");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public void setPeriod(java.lang.Integer period) {
		set("period", period);
	}

	public java.lang.Integer getPeriod() {
		return get("period");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public void setEditdate(java.util.Date editdate) {
		set("editdate", editdate);
	}

	public java.util.Date getEditdate() {
		return get("editdate");
	}

	public void setCreateuser(java.lang.Integer createuser) {
		set("createuser", createuser);
	}

	public java.lang.Integer getCreateuser() {
		return get("createuser");
	}

	public void setEdituser(java.lang.Integer edituser) {
		set("edituser", edituser);
	}

	public java.lang.Integer getEdituser() {
		return get("edituser");
	}

}
