package com.xcrm.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomer<M extends BaseCustomer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCustAddr(java.lang.String custAddr) {
		set("custAddr", custAddr);
	}

	public java.lang.String getCustAddr() {
		return get("custAddr");
	}

	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}

	public java.lang.String getContact() {
		return get("contact");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setCellphone(java.lang.String cellphone) {
		set("cellphone", cellphone);
	}

	public java.lang.String getCellphone() {
		return get("cellphone");
	}

	public void setFax(java.lang.String fax) {
		set("fax", fax);
	}

	public java.lang.String getFax() {
		return get("fax");
	}

	public void setShiptoAddr(java.lang.String shiptoAddr) {
		set("shiptoAddr", shiptoAddr);
	}

	public java.lang.String getShiptoAddr() {
		return get("shiptoAddr");
	}

	public void setCustType(java.lang.Integer custType) {
		set("custType", custType);
	}

	public java.lang.Integer getCustType() {
		return get("custType");
	}

	public void setHeartlevel(java.lang.Integer heartlevel) {
		set("heartlevel", heartlevel);
	}

	public java.lang.Integer getHeartlevel() {
		return get("heartlevel");
	}

	public void setHeartinfo(java.lang.String heartinfo) {
		set("heartinfo", heartinfo);
	}

	public java.lang.String getHeartinfo() {
		return get("heartinfo");
	}

	public void setCreateUser(java.lang.Integer createUser) {
		set("createUser", createUser);
	}

	public java.lang.Integer getCreateUser() {
		return get("createUser");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setUpdateUser(java.lang.Integer updateUser) {
		set("updateUser", updateUser);
	}

	public java.lang.Integer getUpdateUser() {
		return get("updateUser");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	public void setRegionId(java.lang.Integer regionId) {
		set("regionId", regionId);
	}

	public java.lang.Integer getRegionId() {
		return get("regionId");
	}

}