package com.xcrm.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePriceinventoryvalue<M extends BasePriceinventoryvalue<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPriceid(java.lang.Integer priceid) {
		set("priceid", priceid);
	}

	public java.lang.Integer getPriceid() {
		return get("priceid");
	}

	public void setPricekey(java.lang.String pricekey) {
		set("pricekey", pricekey);
	}

	public java.lang.String getPricekey() {
		return get("pricekey");
	}

	public void setPrice(java.lang.Float price) {
		set("price", price);
	}

	public java.lang.Float getPrice() {
		return get("price");
	}

	public void setInventory(java.lang.Integer inventory) {
		set("inventory", inventory);
	}

	public java.lang.Integer getInventory() {
		return get("inventory");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

}
