package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseAttributevalue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attributevalue extends BaseAttributevalue<Attributevalue> {
	public static final Attributevalue dao = new Attributevalue();
}
