package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseAttributeid;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attributeid extends BaseAttributeid<Attributeid> {
	public static final Attributeid dao = new Attributeid();
}
