package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseAttribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attribute extends BaseAttribute<Attribute> implements Comparable<Attribute> {
	public static final Attribute dao = new Attribute();
	
	public Attributeid getAttributeId(){
	  return Attributeid.dao.findFirst( "select * from Attributeid where id= " + this.getAttributeid() );
	}

  public int compareTo( Attribute o ) {
    return o.getAttributeid();
  }
}
