package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseAttribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attribute extends BaseAttribute<Attribute> {
	public static final Attribute dao = new Attribute();
}
