package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseBookitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bookitem extends BaseBookitem<Bookitem> {
	public static final Bookitem dao = new Bookitem();
}
