package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseBookitem;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bookitem extends BaseBookitem<Bookitem> {

  public static final Bookitem dao = new Bookitem();
  public static final int STATUS_INIT = 0;
  public static final int STATUS_ACTIVE = 1;
  public static final int STATUS_CANCELLED = 2;

  public Order getOrder() {
    Orderitem orderitem = Orderitem.dao.findFirst( "select * from orderitem where bookitem = ? ", getId() );
    return Order.dao.findById( orderitem.getOrder() );
  }
}
