package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contract extends BaseContract<Contract> {
	public static final Contract dao = new Contract();
}
