package com.xcrm.common.model;

import java.util.ArrayList;
import java.util.List;

import com.jfinal.plugin.ehcache.CacheKit;
import com.xcrm.common.model.base.BaseDepartment;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {

  private static List<Department> allDepartments = new ArrayList<Department>();
  
  public static final Department dao = new Department();
  
  public static List<Department> getAllDepartments(){
    allDepartments = CacheKit.get( "Department", "all");
    if( allDepartments.isEmpty() ){
      CacheKit.put( "Department", "all", dao.find( "select * from Department" ) );
    }
    return allDepartments;
  }
}
