package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseOrder;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {

  public static final Order dao = new Order();
  public static final int STATUS_ORDER = 1;//'已下订单'
  public static final int STATUS_PARTPAID = 2;//'已付定金'
  public static final int STATUS_ALLPAID = 3;//'已付全款'
  public static final int STATUS_CANCELLED = 4;//'已经取消'

}
