package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseOrderitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orderitem extends BaseOrderitem<Orderitem> {
	public static final Orderitem dao = new Orderitem();
}
