package com.xcrm.common.model;

import java.util.List;

import com.xcrm.common.model.base.BaseOrder;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {

  public static final Order dao = new Order();
  public static final int STATUS_ORDER = 1;//'已下订单'
  public static final int STATUS_PARTPAID = 2;//'已付定金'
  public static final int STATUS_ALLPAID = 3;//'已付全款'
  public static final int STATUS_CANCELLED = 4;//'已经取消'
  
  
  public static final int WORK_STATUS_INIT = 0; //初始态  
  public static final int WORK_STATUS_START = 1; //开始
  public static final int WORK_STATUS_DONE = 2; //完成
  public static final int WORK_STATUS_CANCEL = 3; //取消

  
  public List<Orderitem> getAllOrderitems( ){
    int orderid = this.getId();
    return Orderitem.dao.find( "select * from orderitem where order = " + orderid );
  }
  
  public List<Bookitem> getAllBookitems( ){
    int orderid = this.getId();
    return Bookitem.dao.find(
        "select bi.*,prd.name prdname,IFNULL(wf.workflowtemplate, prd.workflow) workflow,prd.id prdid, wf.id wfid, wf.status wfstatus,(select ppic.fielname from productpic ppic where ppic.productid = prd.id limit 1) fielname "
        + "from bookitem bi "
        + "join product prd on prd.id= bi.product "
        + "join orderitem oi on oi.bookitem = bi.id and oi.order = " + orderid 
        + " left join workflow wf on wf.bookitem = bi.id ");
  }
}
