package com.xcrm.common.model;

import com.xcrm.common.model.base.BasePrdpic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Prdpic extends BasePrdpic<Prdpic> {
	public static final Prdpic dao = new Prdpic();
}
