package com.xcrm.common.model;

import com.xcrm.common.model.base.BasePriceinventoryvalue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Priceinventoryvalue extends BasePriceinventoryvalue<Priceinventoryvalue> {
	public static final Priceinventoryvalue dao = new Priceinventoryvalue();
}
