package com.xcrm.common.model;

import com.xcrm.common.model.base.BasePrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Price extends BasePrice<Price> {
	public static final Price dao = new Price();
}
