package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseProductpic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Productpic extends BaseProductpic<Productpic> {
	public static final Productpic dao = new Productpic();
}
