package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseProductcategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Productcategory extends BaseProductcategory<Productcategory> {
	public static final Productcategory dao = new Productcategory();
}
