package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseSalary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Salary extends BaseSalary<Salary> {
	public static final Salary dao = new Salary();
}
