package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseSalaryitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Salaryitem extends BaseSalaryitem<Salaryitem> {
	public static final Salaryitem dao = new Salaryitem();
}
