package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseSalesseason;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Salesseason extends BaseSalesseason<Salesseason> {
	public static final Salesseason dao = new Salesseason();
}
