package com.xcrm.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.xcrm.common.model.base.BaseWorkflowtemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Workflowtemplate extends BaseWorkflowtemplate<Workflowtemplate> {
	public static final Workflowtemplate dao = new Workflowtemplate();
	
	public List<Workitemtemplate> getWorkitemtemplates( ){
	  return Workitemtemplate.dao.find( "select item.* from Workitemtemplate item "
	      + "join Workflowanditemtemplate ra on ra.workitemtemplate=item.id "
	      + " where ra.workflowtemplate = "  + this.getId());
	}
	
	public List<Record> getWorkitemtemplateRecords( ){
	  return Db.find(  "select item.*,de.name as department from Workitemtemplate item "
          + "join Workflowanditemtemplate ra on ra.workitemtemplate=item.id "
          + "left join Department de on de.id=item.dep "
          + " where ra.workflowtemplate = "  + this.getId() );
    }
	
	public List<Record> listAllActive(){
	  return  Db.find( "select id,name from workflowtemplate where enable = 1" );
	}
	
	public boolean isUsing(){
	  Record p = Db.findFirst( "select * from product where workflow=" + this.getId() );
	  return p != null;
	}
}
