package com.xcrm.common.model;

import java.util.ArrayList;
import java.util.List;

import com.xcrm.common.model.base.BaseWorkflow;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Workflow extends BaseWorkflow<Workflow> {

  public static final Workflow dao = new Workflow();

  public static final int WORK_STATUS_INIT = 0; //待处理 
  public static final int WORK_STATUS_START = 1; //进行中
  public static final int WORK_STATUS_DONE = 2; //已完成
  public static final int WORK_STATUS_CANCEL = 3; //取消
  
  /**
   * 获取同一批(同一个bookitem)Workflow
   * 
   * @return
   */
  public List<Workflow> getRelatedWorkflows( ){
    int bookitemid = this.getBookitem();
    return dao.find( "select wf.*,wft.name name,prd.name prdname,prd.id prdid,bi.num binum "
        + "from workflow wf "
        + "join workflowtemplate wft on wft.id=wf.workflowtemplate "
        + "join bookitem bi on bi.id=wf.bookitem "
        + "join product prd on prd.id=bi.product "
        + "where wf.bookitem=?", bookitemid );
  }
  
  public Bookitem getBookItem( ){
    return Bookitem.dao.findById( getBookitem() );
  }
  
  public List<Productpic> getPrdPictures( ){
    Bookitem bookitem = getBookItem();
    Product product = Product.dao.findById( bookitem.getProduct() ) ;
    if( product != null ){
      return product.getPictures();
    }
    return new ArrayList<>();
  }
  
  public Order getOrder( ){
    Bookitem bookitem = Bookitem.dao.findById( getBookitem() );
    return bookitem.getOrder();
  }
  
  public List<Workitem> getWorkItems( ){
    List<Workitem> items = Workitem.dao.find( "select wi.*,dp.name dp from workitem wi join department dp on dp.id=wi.dep  where wi.workflow=?" , this.getId() );
    items.stream().forEach( i->i.put( "workitemallocations", i.getWorkitemallocations() ) );
    return items;
  }
}
