package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseWorkitemtemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Workitemtemplate extends BaseWorkitemtemplate<Workitemtemplate> {
	public static final Workitemtemplate dao = new Workitemtemplate();
}
