package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseWorkflowanditemtemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Workflowanditemtemplate extends BaseWorkflowanditemtemplate<Workflowanditemtemplate> {
	public static final Workflowanditemtemplate dao = new Workflowanditemtemplate();
}
