package com.xcrm.common.model;

import java.util.List;

import com.xcrm.common.model.base.BaseWorkflowtemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Workflowtemplate extends BaseWorkflowtemplate<Workflowtemplate> {
	public static final Workflowtemplate dao = new Workflowtemplate();
	
	public List<Workitemtemplate> getWorkitemtemplates( ){
	  return Workitemtemplate.dao.find( "select * from Workitemtemplate item "
	      + "join in Workflowanditemtemplate ra on ra.workitemtemplate "
	      + " where ra.workflowtemplate = "  + this.getId());
	}
}
