package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseWorktemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Worktemplate extends BaseWorktemplate<Worktemplate> {
	public static final Worktemplate dao = new Worktemplate();
}
