package com.xcrm.common.model;

import com.xcrm.common.model.base.BaseWorkitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Workitem extends BaseWorkitem<Workitem> {
	public static final Workitem dao = new Workitem();
}
