package com.xcrm.common.model;

import java.util.List;

import com.xcrm.common.model.base.BaseWorkflow;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Workflow extends BaseWorkflow<Workflow> {

  public static final Workflow dao = new Workflow();

  public static final int WORK_STATUS_INIT = 0; //初始态  
  public static final int WORK_STATUS_START = 1; //开始
  public static final int WORK_STATUS_DONE = 2; //完成
  public static final int WORK_STATUS_CANCEL = 3; //取消
  
  /**
   * 获取同一批(同一个bookitem)Workflow
   * 
   * @return
   */
  public List<Workflow> getRelatedWorkflows( ){
    int bookitemid = this.getBookitem();
    return dao.find( "select wf.*,wft.name name,bi.*,prd.name prdname,prd.id prdid "
        + "from workflow wf "
        + "join workflowtemplate wft on wft.id=wf.workflowtemplate "
        + "join bookitem bi on bi.id=wf.bookitem "
        + "join product prd on prd.id=bi.product "
        + "where wf.bookitem=?", bookitemid );
  }
  
  public Bookitem getBookItem( ){
    return Bookitem.dao.findById( getBookitem() );
  }
  
  public Order getOrder( ){
    Bookitem bookitem = Bookitem.dao.findById( getBookitem() );
    return bookitem.getOrder();
  }
}
